/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AuthenticatedInsightRouteImport } from './routes/_authenticated/insight'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedPengurusContributionRouteImport } from './routes/_authenticated/pengurus-contribution'
import { Route as AuthenticatedRecencyAlertsRouteImport } from './routes/_authenticated/recency-alerts'
import { Route as AuthenticatedTeamsRouteImport } from './routes/_authenticated/teams'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events/index'
import { Route as AuthenticatedHomeIndexRouteImport } from './routes/_authenticated/home/index'
import { Route as AuthenticatedHomeAchievementsRouteImport } from './routes/_authenticated/home/achievements'
import { Route as AuthenticatedHomeProfileRouteImport } from './routes/_authenticated/home/profile'
import { Route as AuthenticatedLeaderboardIndexRouteImport } from './routes/_authenticated/leaderboard/index'
import { Route as AuthenticatedConfigureEarlyWarningThresholdRouteImport } from './routes/_authenticated/configure/early-warning/threshold'
import { Route as AuthenticatedConfigureMasterAchievementRouteImport } from './routes/_authenticated/configure/master/achievement'
import { Route as AuthenticatedConfigureMasterAttendanceBadgeRouteImport } from './routes/_authenticated/configure/master/attendance-badge'
import { Route as AuthenticatedConfigureMasterBadgeRouteImport } from './routes/_authenticated/configure/master/badge'
import { Route as AuthenticatedConfigureMasterEventTimeRouteImport } from './routes/_authenticated/configure/master/event-time'
import { Route as AuthenticatedConfigureMasterEventTypeRouteImport } from './routes/_authenticated/configure/master/event-type'
import { Route as AuthenticatedConfigureMasterLevelRouteImport } from './routes/_authenticated/configure/master/level'
import { Route as AuthenticatedConfigureMasterSeasonRouteImport } from './routes/_authenticated/configure/master/season'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInsightRoute = AuthenticatedInsightRouteImport.update({
  id: '/insight',
  path: '/insight',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPengurusContributionRoute =
  AuthenticatedPengurusContributionRouteImport.update({
    id: '/pengurus-contribution',
    path: '/pengurus-contribution',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecencyAlertsRoute =
  AuthenticatedRecencyAlertsRouteImport.update({
    id: '/recency-alerts',
    path: '/recency-alerts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHomeIndexRoute = AuthenticatedHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeAchievementsRoute =
  AuthenticatedHomeAchievementsRouteImport.update({
    id: '/home/achievements',
    path: '/home/achievements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHomeProfileRoute =
  AuthenticatedHomeProfileRouteImport.update({
    id: '/home/profile',
    path: '/home/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeaderboardIndexRoute =
  AuthenticatedLeaderboardIndexRouteImport.update({
    id: '/leaderboard/',
    path: '/leaderboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfigureEarlyWarningThresholdRoute =
  AuthenticatedConfigureEarlyWarningThresholdRouteImport.update({
    id: '/configure/early-warning/threshold',
    path: '/configure/early-warning/threshold',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfigureMasterAchievementRoute =
  AuthenticatedConfigureMasterAchievementRouteImport.update({
    id: '/configure/master/achievement',
    path: '/configure/master/achievement',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfigureMasterAttendanceBadgeRoute =
  AuthenticatedConfigureMasterAttendanceBadgeRouteImport.update({
    id: '/configure/master/attendance-badge',
    path: '/configure/master/attendance-badge',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfigureMasterBadgeRoute =
  AuthenticatedConfigureMasterBadgeRouteImport.update({
    id: '/configure/master/badge',
    path: '/configure/master/badge',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfigureMasterEventTimeRoute =
  AuthenticatedConfigureMasterEventTimeRouteImport.update({
    id: '/configure/master/event-time',
    path: '/configure/master/event-time',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfigureMasterEventTypeRoute =
  AuthenticatedConfigureMasterEventTypeRouteImport.update({
    id: '/configure/master/event-type',
    path: '/configure/master/event-type',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfigureMasterLevelRoute =
  AuthenticatedConfigureMasterLevelRouteImport.update({
    id: '/configure/master/level',
    path: '/configure/master/level',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfigureMasterSeasonRoute =
  AuthenticatedConfigureMasterSeasonRouteImport.update({
    id: '/configure/master/season',
    path: '/configure/master/season',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/insight': typeof AuthenticatedInsightRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/pengurus-contribution': typeof AuthenticatedPengurusContributionRoute
  '/recency-alerts': typeof AuthenticatedRecencyAlertsRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/home/achievements': typeof AuthenticatedHomeAchievementsRoute
  '/home/profile': typeof AuthenticatedHomeProfileRoute
  '/events/': typeof AuthenticatedEventsIndexRoute
  '/home/': typeof AuthenticatedHomeIndexRoute
  '/leaderboard/': typeof AuthenticatedLeaderboardIndexRoute
  '/configure/early-warning/threshold': typeof AuthenticatedConfigureEarlyWarningThresholdRoute
  '/configure/master/achievement': typeof AuthenticatedConfigureMasterAchievementRoute
  '/configure/master/attendance-badge': typeof AuthenticatedConfigureMasterAttendanceBadgeRoute
  '/configure/master/badge': typeof AuthenticatedConfigureMasterBadgeRoute
  '/configure/master/event-time': typeof AuthenticatedConfigureMasterEventTimeRoute
  '/configure/master/event-type': typeof AuthenticatedConfigureMasterEventTypeRoute
  '/configure/master/level': typeof AuthenticatedConfigureMasterLevelRoute
  '/configure/master/season': typeof AuthenticatedConfigureMasterSeasonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/insight': typeof AuthenticatedInsightRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/pengurus-contribution': typeof AuthenticatedPengurusContributionRoute
  '/recency-alerts': typeof AuthenticatedRecencyAlertsRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/home/achievements': typeof AuthenticatedHomeAchievementsRoute
  '/home/profile': typeof AuthenticatedHomeProfileRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/home': typeof AuthenticatedHomeIndexRoute
  '/leaderboard': typeof AuthenticatedLeaderboardIndexRoute
  '/configure/early-warning/threshold': typeof AuthenticatedConfigureEarlyWarningThresholdRoute
  '/configure/master/achievement': typeof AuthenticatedConfigureMasterAchievementRoute
  '/configure/master/attendance-badge': typeof AuthenticatedConfigureMasterAttendanceBadgeRoute
  '/configure/master/badge': typeof AuthenticatedConfigureMasterBadgeRoute
  '/configure/master/event-time': typeof AuthenticatedConfigureMasterEventTimeRoute
  '/configure/master/event-type': typeof AuthenticatedConfigureMasterEventTypeRoute
  '/configure/master/level': typeof AuthenticatedConfigureMasterLevelRoute
  '/configure/master/season': typeof AuthenticatedConfigureMasterSeasonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/_authenticated/insight': typeof AuthenticatedInsightRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/pengurus-contribution': typeof AuthenticatedPengurusContributionRoute
  '/_authenticated/recency-alerts': typeof AuthenticatedRecencyAlertsRoute
  '/_authenticated/teams': typeof AuthenticatedTeamsRoute
  '/_authenticated/home/achievements': typeof AuthenticatedHomeAchievementsRoute
  '/_authenticated/home/profile': typeof AuthenticatedHomeProfileRoute
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
  '/_authenticated/home/': typeof AuthenticatedHomeIndexRoute
  '/_authenticated/leaderboard/': typeof AuthenticatedLeaderboardIndexRoute
  '/_authenticated/configure/early-warning/threshold': typeof AuthenticatedConfigureEarlyWarningThresholdRoute
  '/_authenticated/configure/master/achievement': typeof AuthenticatedConfigureMasterAchievementRoute
  '/_authenticated/configure/master/attendance-badge': typeof AuthenticatedConfigureMasterAttendanceBadgeRoute
  '/_authenticated/configure/master/badge': typeof AuthenticatedConfigureMasterBadgeRoute
  '/_authenticated/configure/master/event-time': typeof AuthenticatedConfigureMasterEventTimeRoute
  '/_authenticated/configure/master/event-type': typeof AuthenticatedConfigureMasterEventTypeRoute
  '/_authenticated/configure/master/level': typeof AuthenticatedConfigureMasterLevelRoute
  '/_authenticated/configure/master/season': typeof AuthenticatedConfigureMasterSeasonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sign-up'
    | '/insight'
    | '/notifications'
    | '/pengurus-contribution'
    | '/recency-alerts'
    | '/teams'
    | '/home/achievements'
    | '/home/profile'
    | '/events/'
    | '/home/'
    | '/leaderboard/'
    | '/configure/early-warning/threshold'
    | '/configure/master/achievement'
    | '/configure/master/attendance-badge'
    | '/configure/master/badge'
    | '/configure/master/event-time'
    | '/configure/master/event-type'
    | '/configure/master/level'
    | '/configure/master/season'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sign-up'
    | '/insight'
    | '/notifications'
    | '/pengurus-contribution'
    | '/recency-alerts'
    | '/teams'
    | '/home/achievements'
    | '/home/profile'
    | '/events'
    | '/home'
    | '/leaderboard'
    | '/configure/early-warning/threshold'
    | '/configure/master/achievement'
    | '/configure/master/attendance-badge'
    | '/configure/master/badge'
    | '/configure/master/event-time'
    | '/configure/master/event-type'
    | '/configure/master/level'
    | '/configure/master/season'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/sign-up'
    | '/_authenticated/insight'
    | '/_authenticated/notifications'
    | '/_authenticated/pengurus-contribution'
    | '/_authenticated/recency-alerts'
    | '/_authenticated/teams'
    | '/_authenticated/home/achievements'
    | '/_authenticated/home/profile'
    | '/_authenticated/events/'
    | '/_authenticated/home/'
    | '/_authenticated/leaderboard/'
    | '/_authenticated/configure/early-warning/threshold'
    | '/_authenticated/configure/master/achievement'
    | '/_authenticated/configure/master/attendance-badge'
    | '/_authenticated/configure/master/badge'
    | '/_authenticated/configure/master/event-time'
    | '/_authenticated/configure/master/event-type'
    | '/_authenticated/configure/master/level'
    | '/_authenticated/configure/master/season'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/insight': {
      id: '/_authenticated/insight'
      path: '/insight'
      fullPath: '/insight'
      preLoaderRoute: typeof AuthenticatedInsightRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pengurus-contribution': {
      id: '/_authenticated/pengurus-contribution'
      path: '/pengurus-contribution'
      fullPath: '/pengurus-contribution'
      preLoaderRoute: typeof AuthenticatedPengurusContributionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recency-alerts': {
      id: '/_authenticated/recency-alerts'
      path: '/recency-alerts'
      fullPath: '/recency-alerts'
      preLoaderRoute: typeof AuthenticatedRecencyAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home/': {
      id: '/_authenticated/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof AuthenticatedHomeIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home/achievements': {
      id: '/_authenticated/home/achievements'
      path: '/home/achievements'
      fullPath: '/home/achievements'
      preLoaderRoute: typeof AuthenticatedHomeAchievementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home/profile': {
      id: '/_authenticated/home/profile'
      path: '/home/profile'
      fullPath: '/home/profile'
      preLoaderRoute: typeof AuthenticatedHomeProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leaderboard/': {
      id: '/_authenticated/leaderboard/'
      path: '/leaderboard'
      fullPath: '/leaderboard/'
      preLoaderRoute: typeof AuthenticatedLeaderboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configure/early-warning/threshold': {
      id: '/_authenticated/configure/early-warning/threshold'
      path: '/configure/early-warning/threshold'
      fullPath: '/configure/early-warning/threshold'
      preLoaderRoute: typeof AuthenticatedConfigureEarlyWarningThresholdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configure/master/achievement': {
      id: '/_authenticated/configure/master/achievement'
      path: '/configure/master/achievement'
      fullPath: '/configure/master/achievement'
      preLoaderRoute: typeof AuthenticatedConfigureMasterAchievementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configure/master/attendance-badge': {
      id: '/_authenticated/configure/master/attendance-badge'
      path: '/configure/master/attendance-badge'
      fullPath: '/configure/master/attendance-badge'
      preLoaderRoute: typeof AuthenticatedConfigureMasterAttendanceBadgeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configure/master/badge': {
      id: '/_authenticated/configure/master/badge'
      path: '/configure/master/badge'
      fullPath: '/configure/master/badge'
      preLoaderRoute: typeof AuthenticatedConfigureMasterBadgeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configure/master/event-time': {
      id: '/_authenticated/configure/master/event-time'
      path: '/configure/master/event-time'
      fullPath: '/configure/master/event-time'
      preLoaderRoute: typeof AuthenticatedConfigureMasterEventTimeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configure/master/event-type': {
      id: '/_authenticated/configure/master/event-type'
      path: '/configure/master/event-type'
      fullPath: '/configure/master/event-type'
      preLoaderRoute: typeof AuthenticatedConfigureMasterEventTypeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configure/master/level': {
      id: '/_authenticated/configure/master/level'
      path: '/configure/master/level'
      fullPath: '/configure/master/level'
      preLoaderRoute: typeof AuthenticatedConfigureMasterLevelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configure/master/season': {
      id: '/_authenticated/configure/master/season'
      path: '/configure/master/season'
      fullPath: '/configure/master/season'
      preLoaderRoute: typeof AuthenticatedConfigureMasterSeasonRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedInsightRoute: typeof AuthenticatedInsightRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPengurusContributionRoute: typeof AuthenticatedPengurusContributionRoute
  AuthenticatedRecencyAlertsRoute: typeof AuthenticatedRecencyAlertsRoute
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRoute
  AuthenticatedHomeAchievementsRoute: typeof AuthenticatedHomeAchievementsRoute
  AuthenticatedHomeProfileRoute: typeof AuthenticatedHomeProfileRoute
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
  AuthenticatedHomeIndexRoute: typeof AuthenticatedHomeIndexRoute
  AuthenticatedLeaderboardIndexRoute: typeof AuthenticatedLeaderboardIndexRoute
  AuthenticatedConfigureEarlyWarningThresholdRoute: typeof AuthenticatedConfigureEarlyWarningThresholdRoute
  AuthenticatedConfigureMasterAchievementRoute: typeof AuthenticatedConfigureMasterAchievementRoute
  AuthenticatedConfigureMasterAttendanceBadgeRoute: typeof AuthenticatedConfigureMasterAttendanceBadgeRoute
  AuthenticatedConfigureMasterBadgeRoute: typeof AuthenticatedConfigureMasterBadgeRoute
  AuthenticatedConfigureMasterEventTimeRoute: typeof AuthenticatedConfigureMasterEventTimeRoute
  AuthenticatedConfigureMasterEventTypeRoute: typeof AuthenticatedConfigureMasterEventTypeRoute
  AuthenticatedConfigureMasterLevelRoute: typeof AuthenticatedConfigureMasterLevelRoute
  AuthenticatedConfigureMasterSeasonRoute: typeof AuthenticatedConfigureMasterSeasonRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedInsightRoute: AuthenticatedInsightRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPengurusContributionRoute:
    AuthenticatedPengurusContributionRoute,
  AuthenticatedRecencyAlertsRoute: AuthenticatedRecencyAlertsRoute,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRoute,
  AuthenticatedHomeAchievementsRoute: AuthenticatedHomeAchievementsRoute,
  AuthenticatedHomeProfileRoute: AuthenticatedHomeProfileRoute,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
  AuthenticatedHomeIndexRoute: AuthenticatedHomeIndexRoute,
  AuthenticatedLeaderboardIndexRoute: AuthenticatedLeaderboardIndexRoute,
  AuthenticatedConfigureEarlyWarningThresholdRoute:
    AuthenticatedConfigureEarlyWarningThresholdRoute,
  AuthenticatedConfigureMasterAchievementRoute:
    AuthenticatedConfigureMasterAchievementRoute,
  AuthenticatedConfigureMasterAttendanceBadgeRoute:
    AuthenticatedConfigureMasterAttendanceBadgeRoute,
  AuthenticatedConfigureMasterBadgeRoute:
    AuthenticatedConfigureMasterBadgeRoute,
  AuthenticatedConfigureMasterEventTimeRoute:
    AuthenticatedConfigureMasterEventTimeRoute,
  AuthenticatedConfigureMasterEventTypeRoute:
    AuthenticatedConfigureMasterEventTypeRoute,
  AuthenticatedConfigureMasterLevelRoute:
    AuthenticatedConfigureMasterLevelRoute,
  AuthenticatedConfigureMasterSeasonRoute:
    AuthenticatedConfigureMasterSeasonRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
