version: "3.8"

services:
  sekkha-api:
    image: ferdignatius/sekkha-api:v1.3.0
    container_name: sekkha-api
    restart: unless-stopped


    env_file:
      - .env

    networks:
      - proxy-tier
      - data-tier

    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          memory: 128M

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  proxy-tier:
    external: true
  data-tier:
    external: true


