/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard/profile'
import { Route as AuthenticatedConfigureMasterLevelRouteImport } from './routes/_authenticated/configure/master/level'
import { Route as AuthenticatedConfigureMasterEventTypeRouteImport } from './routes/_authenticated/configure/master/event-type'
import { Route as AuthenticatedConfigureMasterBadgeRouteImport } from './routes/_authenticated/configure/master/badge'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/dashboard/profile',
    path: '/dashboard/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfigureMasterLevelRoute =
  AuthenticatedConfigureMasterLevelRouteImport.update({
    id: '/configure/master/level',
    path: '/configure/master/level',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfigureMasterEventTypeRoute =
  AuthenticatedConfigureMasterEventTypeRouteImport.update({
    id: '/configure/master/event-type',
    path: '/configure/master/event-type',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfigureMasterBadgeRoute =
  AuthenticatedConfigureMasterBadgeRouteImport.update({
    id: '/configure/master/badge',
    path: '/configure/master/badge',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/events/': typeof AuthenticatedEventsIndexRoute
  '/configure/master/badge': typeof AuthenticatedConfigureMasterBadgeRoute
  '/configure/master/event-type': typeof AuthenticatedConfigureMasterEventTypeRoute
  '/configure/master/level': typeof AuthenticatedConfigureMasterLevelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/configure/master/badge': typeof AuthenticatedConfigureMasterBadgeRoute
  '/configure/master/event-type': typeof AuthenticatedConfigureMasterEventTypeRoute
  '/configure/master/level': typeof AuthenticatedConfigureMasterLevelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
  '/_authenticated/configure/master/badge': typeof AuthenticatedConfigureMasterBadgeRoute
  '/_authenticated/configure/master/event-type': typeof AuthenticatedConfigureMasterEventTypeRoute
  '/_authenticated/configure/master/level': typeof AuthenticatedConfigureMasterLevelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sign-up'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/events/'
    | '/configure/master/badge'
    | '/configure/master/event-type'
    | '/configure/master/level'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sign-up'
    | '/dashboard/profile'
    | '/dashboard'
    | '/events'
    | '/configure/master/badge'
    | '/configure/master/event-type'
    | '/configure/master/level'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/sign-up'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/'
    | '/_authenticated/events/'
    | '/_authenticated/configure/master/badge'
    | '/_authenticated/configure/master/event-type'
    | '/_authenticated/configure/master/level'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configure/master/level': {
      id: '/_authenticated/configure/master/level'
      path: '/configure/master/level'
      fullPath: '/configure/master/level'
      preLoaderRoute: typeof AuthenticatedConfigureMasterLevelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configure/master/event-type': {
      id: '/_authenticated/configure/master/event-type'
      path: '/configure/master/event-type'
      fullPath: '/configure/master/event-type'
      preLoaderRoute: typeof AuthenticatedConfigureMasterEventTypeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configure/master/badge': {
      id: '/_authenticated/configure/master/badge'
      path: '/configure/master/badge'
      fullPath: '/configure/master/badge'
      preLoaderRoute: typeof AuthenticatedConfigureMasterBadgeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
  AuthenticatedConfigureMasterBadgeRoute: typeof AuthenticatedConfigureMasterBadgeRoute
  AuthenticatedConfigureMasterEventTypeRoute: typeof AuthenticatedConfigureMasterEventTypeRoute
  AuthenticatedConfigureMasterLevelRoute: typeof AuthenticatedConfigureMasterLevelRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
  AuthenticatedConfigureMasterBadgeRoute:
    AuthenticatedConfigureMasterBadgeRoute,
  AuthenticatedConfigureMasterEventTypeRoute:
    AuthenticatedConfigureMasterEventTypeRoute,
  AuthenticatedConfigureMasterLevelRoute:
    AuthenticatedConfigureMasterLevelRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
