/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedInsightRouteImport } from './routes/_authenticated/insight'
import { Route as AuthenticatedAnalysisRouteImport } from './routes/_authenticated/analysis'
import { Route as AuthenticatedLeaderboardIndexRouteImport } from './routes/_authenticated/leaderboard/index'
import { Route as AuthenticatedHomeIndexRouteImport } from './routes/_authenticated/home/index'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events/index'
import { Route as AuthenticatedCommunityIndexRouteImport } from './routes/_authenticated/community/index'
import { Route as AuthenticatedHomeProfileRouteImport } from './routes/_authenticated/home/profile'
import { Route as AuthenticatedHomeAchievementsRouteImport } from './routes/_authenticated/home/achievements'
import { Route as AuthenticatedConfigureMasterLevelRouteImport } from './routes/_authenticated/configure/master/level'
import { Route as AuthenticatedConfigureMasterEventTypeRouteImport } from './routes/_authenticated/configure/master/event-type'
import { Route as AuthenticatedConfigureMasterBadgeRouteImport } from './routes/_authenticated/configure/master/badge'
import { Route as AuthenticatedConfigureMasterAchievementRouteImport } from './routes/_authenticated/configure/master/achievement'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInsightRoute = AuthenticatedInsightRouteImport.update({
  id: '/insight',
  path: '/insight',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalysisRoute = AuthenticatedAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaderboardIndexRoute =
  AuthenticatedLeaderboardIndexRouteImport.update({
    id: '/leaderboard/',
    path: '/leaderboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHomeIndexRoute = AuthenticatedHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommunityIndexRoute =
  AuthenticatedCommunityIndexRouteImport.update({
    id: '/community/',
    path: '/community/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHomeProfileRoute =
  AuthenticatedHomeProfileRouteImport.update({
    id: '/home/profile',
    path: '/home/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHomeAchievementsRoute =
  AuthenticatedHomeAchievementsRouteImport.update({
    id: '/home/achievements',
    path: '/home/achievements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfigureMasterLevelRoute =
  AuthenticatedConfigureMasterLevelRouteImport.update({
    id: '/configure/master/level',
    path: '/configure/master/level',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfigureMasterEventTypeRoute =
  AuthenticatedConfigureMasterEventTypeRouteImport.update({
    id: '/configure/master/event-type',
    path: '/configure/master/event-type',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfigureMasterBadgeRoute =
  AuthenticatedConfigureMasterBadgeRouteImport.update({
    id: '/configure/master/badge',
    path: '/configure/master/badge',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfigureMasterAchievementRoute =
  AuthenticatedConfigureMasterAchievementRouteImport.update({
    id: '/configure/master/achievement',
    path: '/configure/master/achievement',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/analysis': typeof AuthenticatedAnalysisRoute
  '/insight': typeof AuthenticatedInsightRoute
  '/home/achievements': typeof AuthenticatedHomeAchievementsRoute
  '/home/profile': typeof AuthenticatedHomeProfileRoute
  '/community/': typeof AuthenticatedCommunityIndexRoute
  '/events/': typeof AuthenticatedEventsIndexRoute
  '/home/': typeof AuthenticatedHomeIndexRoute
  '/leaderboard/': typeof AuthenticatedLeaderboardIndexRoute
  '/configure/master/achievement': typeof AuthenticatedConfigureMasterAchievementRoute
  '/configure/master/badge': typeof AuthenticatedConfigureMasterBadgeRoute
  '/configure/master/event-type': typeof AuthenticatedConfigureMasterEventTypeRoute
  '/configure/master/level': typeof AuthenticatedConfigureMasterLevelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/analysis': typeof AuthenticatedAnalysisRoute
  '/insight': typeof AuthenticatedInsightRoute
  '/home/achievements': typeof AuthenticatedHomeAchievementsRoute
  '/home/profile': typeof AuthenticatedHomeProfileRoute
  '/community': typeof AuthenticatedCommunityIndexRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/home': typeof AuthenticatedHomeIndexRoute
  '/leaderboard': typeof AuthenticatedLeaderboardIndexRoute
  '/configure/master/achievement': typeof AuthenticatedConfigureMasterAchievementRoute
  '/configure/master/badge': typeof AuthenticatedConfigureMasterBadgeRoute
  '/configure/master/event-type': typeof AuthenticatedConfigureMasterEventTypeRoute
  '/configure/master/level': typeof AuthenticatedConfigureMasterLevelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/_authenticated/analysis': typeof AuthenticatedAnalysisRoute
  '/_authenticated/insight': typeof AuthenticatedInsightRoute
  '/_authenticated/home/achievements': typeof AuthenticatedHomeAchievementsRoute
  '/_authenticated/home/profile': typeof AuthenticatedHomeProfileRoute
  '/_authenticated/community/': typeof AuthenticatedCommunityIndexRoute
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
  '/_authenticated/home/': typeof AuthenticatedHomeIndexRoute
  '/_authenticated/leaderboard/': typeof AuthenticatedLeaderboardIndexRoute
  '/_authenticated/configure/master/achievement': typeof AuthenticatedConfigureMasterAchievementRoute
  '/_authenticated/configure/master/badge': typeof AuthenticatedConfigureMasterBadgeRoute
  '/_authenticated/configure/master/event-type': typeof AuthenticatedConfigureMasterEventTypeRoute
  '/_authenticated/configure/master/level': typeof AuthenticatedConfigureMasterLevelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sign-up'
    | '/analysis'
    | '/insight'
    | '/home/achievements'
    | '/home/profile'
    | '/community/'
    | '/events/'
    | '/home/'
    | '/leaderboard/'
    | '/configure/master/achievement'
    | '/configure/master/badge'
    | '/configure/master/event-type'
    | '/configure/master/level'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sign-up'
    | '/analysis'
    | '/insight'
    | '/home/achievements'
    | '/home/profile'
    | '/community'
    | '/events'
    | '/home'
    | '/leaderboard'
    | '/configure/master/achievement'
    | '/configure/master/badge'
    | '/configure/master/event-type'
    | '/configure/master/level'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/sign-up'
    | '/_authenticated/analysis'
    | '/_authenticated/insight'
    | '/_authenticated/home/achievements'
    | '/_authenticated/home/profile'
    | '/_authenticated/community/'
    | '/_authenticated/events/'
    | '/_authenticated/home/'
    | '/_authenticated/leaderboard/'
    | '/_authenticated/configure/master/achievement'
    | '/_authenticated/configure/master/badge'
    | '/_authenticated/configure/master/event-type'
    | '/_authenticated/configure/master/level'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/insight': {
      id: '/_authenticated/insight'
      path: '/insight'
      fullPath: '/insight'
      preLoaderRoute: typeof AuthenticatedInsightRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analysis': {
      id: '/_authenticated/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AuthenticatedAnalysisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leaderboard/': {
      id: '/_authenticated/leaderboard/'
      path: '/leaderboard'
      fullPath: '/leaderboard/'
      preLoaderRoute: typeof AuthenticatedLeaderboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home/': {
      id: '/_authenticated/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof AuthenticatedHomeIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/community/': {
      id: '/_authenticated/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof AuthenticatedCommunityIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home/profile': {
      id: '/_authenticated/home/profile'
      path: '/home/profile'
      fullPath: '/home/profile'
      preLoaderRoute: typeof AuthenticatedHomeProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home/achievements': {
      id: '/_authenticated/home/achievements'
      path: '/home/achievements'
      fullPath: '/home/achievements'
      preLoaderRoute: typeof AuthenticatedHomeAchievementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configure/master/level': {
      id: '/_authenticated/configure/master/level'
      path: '/configure/master/level'
      fullPath: '/configure/master/level'
      preLoaderRoute: typeof AuthenticatedConfigureMasterLevelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configure/master/event-type': {
      id: '/_authenticated/configure/master/event-type'
      path: '/configure/master/event-type'
      fullPath: '/configure/master/event-type'
      preLoaderRoute: typeof AuthenticatedConfigureMasterEventTypeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configure/master/badge': {
      id: '/_authenticated/configure/master/badge'
      path: '/configure/master/badge'
      fullPath: '/configure/master/badge'
      preLoaderRoute: typeof AuthenticatedConfigureMasterBadgeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configure/master/achievement': {
      id: '/_authenticated/configure/master/achievement'
      path: '/configure/master/achievement'
      fullPath: '/configure/master/achievement'
      preLoaderRoute: typeof AuthenticatedConfigureMasterAchievementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnalysisRoute: typeof AuthenticatedAnalysisRoute
  AuthenticatedInsightRoute: typeof AuthenticatedInsightRoute
  AuthenticatedHomeAchievementsRoute: typeof AuthenticatedHomeAchievementsRoute
  AuthenticatedHomeProfileRoute: typeof AuthenticatedHomeProfileRoute
  AuthenticatedCommunityIndexRoute: typeof AuthenticatedCommunityIndexRoute
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
  AuthenticatedHomeIndexRoute: typeof AuthenticatedHomeIndexRoute
  AuthenticatedLeaderboardIndexRoute: typeof AuthenticatedLeaderboardIndexRoute
  AuthenticatedConfigureMasterAchievementRoute: typeof AuthenticatedConfigureMasterAchievementRoute
  AuthenticatedConfigureMasterBadgeRoute: typeof AuthenticatedConfigureMasterBadgeRoute
  AuthenticatedConfigureMasterEventTypeRoute: typeof AuthenticatedConfigureMasterEventTypeRoute
  AuthenticatedConfigureMasterLevelRoute: typeof AuthenticatedConfigureMasterLevelRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalysisRoute: AuthenticatedAnalysisRoute,
  AuthenticatedInsightRoute: AuthenticatedInsightRoute,
  AuthenticatedHomeAchievementsRoute: AuthenticatedHomeAchievementsRoute,
  AuthenticatedHomeProfileRoute: AuthenticatedHomeProfileRoute,
  AuthenticatedCommunityIndexRoute: AuthenticatedCommunityIndexRoute,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
  AuthenticatedHomeIndexRoute: AuthenticatedHomeIndexRoute,
  AuthenticatedLeaderboardIndexRoute: AuthenticatedLeaderboardIndexRoute,
  AuthenticatedConfigureMasterAchievementRoute:
    AuthenticatedConfigureMasterAchievementRoute,
  AuthenticatedConfigureMasterBadgeRoute:
    AuthenticatedConfigureMasterBadgeRoute,
  AuthenticatedConfigureMasterEventTypeRoute:
    AuthenticatedConfigureMasterEventTypeRoute,
  AuthenticatedConfigureMasterLevelRoute:
    AuthenticatedConfigureMasterLevelRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
